<?php
include('../model/lib/connect.php');
include('../model/LoaiSanPham.php');
include('../model/SanPham.php');
include('../model/KhuyenMai.php');
include('../model/ChiTietSanPham.php');
include('../model/Mau.php');
include('../model/thanhvien.php');
include('../model/GioHang.php');
include('../model/ChiTietGioHang.php');
include('../model/QuangCao.php');

include('../controller/category.php');
include('../controller/product.php');
include('../controller/promotion.php');
include('../controller/product_details.php');
include('../controller/color.php');
include('../controller/member.php');
include('../controller/cart.php');
include('../controller/cart_detail.php');
include('../controller/advertisement.php');
